### PR TITLE
Convert Action to TypeScript

### PR DESCRIPTION
**Pull request by LouisMT**
Convert the Action from Docker + Bash to TypeScript/JavaScript.

Advantages:
* Can run natively in GitHub Actions: doesn't require time to build a Docker image first
* Easier to add tests
* Easier to extend functionality (an authorized GitHub client is available out of the box)

### CODE REVIEW

**Review by juulSme — APPROVED** [review]
Looks great to me!

**Comment by juulSme** [comment]
Is it necessary to go `v3` though? Isn't it backwards compatible with v2?

**Comment by LouisMT** [comment]
It should be, at least that was my intention. I'll make sure that it is, and then we can merge this!

**Comment by juulSme** [comment]
We could test if for a little while in a `v2-beta` branch or something and release it into `v2` afterwards.

**Comment by LouisMT** [comment]
Sounds good, we can tag v2-beta to try it out first.

**Pull request merged**
